### PR TITLE
Enables Axom to be configured without MPI when (some of) its dependencies use MPI

### LINKED ISSUE #1944: error building quest w/o mpi
axom develop, build on dane using gcc 10.3 (I used this compiler b/c I have a conduit tpls built with this compiler)

```
      |                                                 ^
In file included from /usr/WS1/visit/visit/thirdparty_shared/3.5.0/toss4/hdf5/2.0.0/linux-x86_64_gcc-10.3/include/H5public.h:51,
                 from /usr/WS1/visit/visit/thirdparty_shared/3.5.0/toss4/hdf5/2.0.0/linux-x86_64_gcc-10.3/include/hdf5.h:21,
                 from /usr/workspace/cyrush/2026.08.axom/axom/src/axom/core/../../axom/sidre/core/Group.hpp:41,
                 from /usr/workspace/cyrush/2026.08.axom/build/include/axom/sidre.hpp:16,
                 from /usr/workspace/cyrush/2026.08.axom/axom/src/axom/core/../../axom/mint/mesh/FieldData.hpp:14,
                 from /usr/workspace/cyrush/2026.08.axom/axom/src/axom/core/../../axom/mint/mesh/Mesh.hpp:14,
                 from /usr/workspace/cyrush/2026.08.axom/axom/src/axom/core/../../axom/quest/interface/internal/QuestHelpers.hpp:13,
                 from /usr/workspace/cyrush/2026.08.axom/axom/src/axom/quest/interface/internal/QuestHelpers.cpp:7:
/usr/workspace/cyrush/2026.08.axom/axom/src/axom/core/../../axom/quest/interface/internal/mpicomm_wrapper.hpp:25:15: error: expected ‘)’ before numeric constant
   25 | constexpr int MPI_COMM_SELF = -1;
      |               ^~~~~~~~~~~~~
```

Maybe this is an issue with gcc 10.3's C++20 support, but it seems like constexpr should be fine?

### PR DESCRIPTION
**Pull request by kennyweiss**
# Summary

- This PR is a feature/bugfix
- It allows Axom to be configured without MPI (`ENABLE_MPI=OFF`) when (some of) its dependencies were configured with MPI
  - It removes Quest's fake `MPI_COMM` definitions in favor of an internal `CommHandle` definition to avoid reusing MPI symbols
  - Removes a possible footgun that would read meshes on all ranks if the MPI_Comm/CommHandle parameter was missing
- Most of this was internal Axom implementations (e.g. in the internal `QuestHelpers`), and should minimally affect users (unless they were using internal implementations, in which case the upgrade should be straightforward)
- Resolves #1944

### CODE REVIEW

File: src/axom/quest/interface/internal/QuestHelpers.hpp [hunk 1]
```diff
@@ -11,32 +11,77 @@
...
+{
+  Serial = -1
+};
+
+/// \brief Returns a handle for the calling rank alone
+inline CommHandle commSelf() { return CommHandle::Serial; }
+
+/// \brief Returns a handle for all ranks
+inline CommHandle commWorld() { return CommHandle::Serial; }
+#endif
```
Comment (kennyweiss) [inline src/axom/quest/interface/internal/QuestHelpers.hpp:77]: We're now using `CommHandle` instead of faking `MPI_Comm` in API calls that can optionally support MPI.  Most of these were only in internal APIs  (e.g. in an `axom::*::internal` namespace).

Using a fake `MPI_Comm` was problematic when Axom was configured without MPI but some of its dependencies were configured with MPI since those could bring in MPI defines.

File: src/axom/quest/interface/inout.cpp [hunk 2]
```diff
@@ -392,6 +394,24 @@ int inout_init(std::shared_ptr<mint::Mesh>& mesh, MPI_Comm comm)
...
+}
+
+#if defined(AXOM_USE_MPI)
+int inout_init(const std::string& file, MPI_Comm comm) { return inout_init_impl(file, comm); }
+
+int inout_init(std::shared_ptr<mint::Mesh>& mesh, MPI_Comm comm)
+{
+  return inout_init_impl(mesh, comm);
+}
+#endif
```
Comment (kennyweiss) [inline src/axom/quest/interface/inout.cpp:413]: Note that the public API only has an MPI comm parameter when Axom is configured w/ MPI.

File: src/axom/quest/DiscreteShape.hpp [hunk 3]
```diff
@@ -12,21 +12,20 @@
...
 /*!
-  @brief Post-processed klee::Shape, with the geometry discretized and transformed
-  according to the Shape's operators.
-
-  TODO: Move this class into internal namespace.
-*/
+ * @brief Post-processed klee::Shape, with the geometry discretized and transformed
+ * according to the Shape's operators.
+ *
+ * TODO: Move this class into internal namespace.
```
Comment (kennyweiss) [inline src/axom/quest/DiscreteShape.hpp:27]: This TODO is interesting. 
I will look into whether this class is actually internal and if the repercussions, if any, of moving it to the `internal` namespace.

File: src/axom/quest/interface/internal/QuestHelpers.hpp (hunk 1 above)
Comment (cyrush) [reply src/axom/quest/interface/internal/QuestHelpers.hpp:77]: In Ascent, we use the fortran mpi handle (always an integer) b/c interface can get messy due various ways MPI_Comm is implemented. 

We can always convert this to an MPI_Comm when needed

File: src/cmake/thirdparty/SetupAxomThirdParty.cmake [hunk 4]
```diff
@@ -192,6 +192,11 @@ else()
     message(STATUS "MFEM support is OFF")
 endif()
 
+# MFEM's exported target does not always propagate its MPI dependency.
+if(TARGET mfem AND MFEM_USE_MPI)
+    blt_patch_target(NAME mfem DEPENDS_ON mpi)
+endif()
```
Comment (kennyweiss) [inline src/cmake/thirdparty/SetupAxomThirdParty.cmake:198]: I think this can be resolved more robustly once we use language-dependent MPI targets, and posted a comment to the relevant issue -- https://github.com/llnl/axom/issues/1853#issuecomment-5348492067

File: src/axom/core/tests/utils_config.cpp [hunk 5]
```diff
@@ -100,12 +100,6 @@ TEST(utils_config, mfem_configuration)
     mfemHasMPI = true;
   #endif
     std::cout << "mfem is built " << (mfemHasMPI ? "with" : "without") << " MPI" << std::endl;
-
-    if(!axomHasMPI)
-    {
-      EXPECT_FALSE(mfemHasMPI) << "Axom expects mfem to be built without MPI "
-                                  "when it is not built with MPI";
-    }
```
Comment (bmhan12) [inline src/axom/core/tests/utils_config.cpp]: Is this check being handled somewhere else or is redundant?

**Review by bmhan12 — APPROVED** [review]

**Review by Arlie-Capps — APPROVED** [review]
Thanks for this fix, Kenny.
