### ISSUE TITLE
error building quest w/o mpi

### ISSUE THREAD

**Issue by cyrush** [llnl/axom#1944]
axom develop, build on dane using gcc 10.3 (I used this compiler b/c I have a conduit tpls built with this compiler)

```
      |                                                 ^
In file included from /usr/WS1/visit/visit/thirdparty_shared/3.5.0/toss4/hdf5/2.0.0/linux-x86_64_gcc-10.3/include/H5public.h:51,
                 from /usr/WS1/visit/visit/thirdparty_shared/3.5.0/toss4/hdf5/2.0.0/linux-x86_64_gcc-10.3/include/hdf5.h:21,
                 from /usr/workspace/cyrush/2026.08.axom/axom/src/axom/core/../../axom/sidre/core/Group.hpp:41,
                 from /usr/workspace/cyrush/2026.08.axom/build/include/axom/sidre.hpp:16,
                 from /usr/workspace/cyrush/2026.08.axom/axom/src/axom/core/../../axom/mint/mesh/FieldData.hpp:14,
                 from /usr/workspace/cyrush/2026.08.axom/axom/src/axom/core/../../axom/mint/mesh/Mesh.hpp:14,
                 from /usr/workspace/cyrush/2026.08.axom/axom/src/axom/core/../../axom/quest/interface/internal/QuestHelpers.hpp:13,
                 from /usr/workspace/cyrush/2026.08.axom/axom/src/axom/quest/interface/internal/QuestHelpers.cpp:7:
/usr/workspace/cyrush/2026.08.axom/axom/src/axom/core/../../axom/quest/interface/internal/mpicomm_wrapper.hpp:25:15: error: expected ‘)’ before numeric constant
   25 | constexpr int MPI_COMM_SELF = -1;
      |               ^~~~~~~~~~~~~
```

Maybe this is an issue with gcc 10.3's C++20 support, but it seems like constexpr should be fine?

**Comment by cyrush** [comment]
Also happens with gcc 13.

```
[ 86%] Building CXX object axom/quest/CMakeFiles/quest.dir/interface/internal/QuestHelpers.cpp.o
In file included from /usr/WS1/visit/visit/thirdparty_shared/3.5.0/toss4/hdf5/2.0.0/linux-x86_64_gcc-10.3/include/H5public.h:51,
                 from /usr/WS1/visit/visit/thirdparty_shared/3.5.0/toss4/hdf5/2.0.0/linux-x86_64_gcc-10.3/include/hdf5.h:21,
                 from /usr/workspace/cyrush/2026.08.axom/axom/src/axom/core/../../axom/sidre/core/Group.hpp:41,
                 from /usr/workspace/cyrush/2026.08.axom/build_13/include/axom/sidre.hpp:16,
                 from /usr/workspace/cyrush/2026.08.axom/axom/src/axom/core/../../axom/mint/mesh/FieldData.hpp:14,
                 from /usr/workspace/cyrush/2026.08.axom/axom/src/axom/core/../../axom/mint/mesh/Mesh.hpp:14,
                 from /usr/workspace/cyrush/2026.08.axom/axom/src/axom/core/../../axom/quest/interface/internal/QuestHelpers.hpp:13,
                 from /usr/workspace/cyrush/2026.08.axom/axom/src/axom/quest/interface/internal/QuestHelpers.cpp:7:
/usr/workspace/cyrush/2026.08.axom/axom/src/axom/core/../../axom/quest/interface/internal/mpicomm_wrapper.hpp:25:15: error: expected ‘)’ before numeric constant
   25 | constexpr int MPI_COMM_SELF = -1;

```

**Comment by BradWhitlock** [comment]
Maybe axom was not told to build with MPI but some 3rd party includes it? I wonder whether `#undef MPI_COMM_SELF` there would work around it.

**Comment by cyrush** [comment]
I suspect this is a conflict with HDF5's use of MPI, but I can't quite pin it down.

**Comment by cyrush** [comment]
Looks like the error is where hdf5 public does  `#include <mpi.h>`

**Comment by kennyweiss** [comment]
We might want to just remove the `MPI_COMM_SELF` from quest instead of trying to fake MPI support in cases where it's not available.
