### ISSUE TITLE
Update to Shroud 0.13

### ISSUE THREAD

**Issue by ltaylor16** [LLNL/axom#1258]
The current version of Shroud in devtools is not working with Python 3.10.

    File "/collab/usr/gapps/axom/devtools/toss_4_x86_64_ib/2023_10_17_16_15_32/._view/ypfidjpdm7fhkqcpekza67w5xgiaw7yg/python-3.10.10/lib/python3.10/site-packages/shroud/typemap.py", line 247, in __export_yaml__
      util.as_yaml(self, order, output)
    File "/collab/usr/gapps/axom/devtools/toss_4_x86_64_ib/2023_10_17_16_15_32/._view/ypfidjpdm7fhkqcpekza67w5xgiaw7yg/python-3.10.10/lib/python3.10/site-packages/shroud/util.py", line 113, in as_yaml
      if isinstance(obj, collections.Mapping):
    AttributeError: module 'collections' has no attribute 'Mapping'

- [x] Add version 0.13.0 to spack  `var/spack/repos/builtin/packages/py-shroud`
- [x] Update devtools to Shroud-0.13
- [x] Update YAML files to Shroud changes

**Comment by kennyweiss** [comment]
spack-packages has versions for `shroud@0.13` and `shroud@0.14`

See: 
* https://github.com/spack/spack-packages/blob/develop/repos/spack_repo/builtin/packages/py_shroud/package.py
* @white238's PR -- https://github.com/spack/spack-packages/pull/2637
