### ISSUE TITLE
axom-0.7.0_2 fails to build with mfem-4.5.2: error: no member named 'GetElementIntRule' in 'mfem::QuadratureSpaceBase'

### ISSUE THREAD

**Issue by yurivict** [LLNL/axom#1118]
```
/wrkdirs/usr/ports/science/axom/work/axom-0.7.0/src/axom/sidre/core/MFEMSidreDataCollection.cpp:1119:15: warning: unused variable 'num_domains' [-Wunused-variable]
        View* num_domains = 
              ^
/wrkdirs/usr/ports/science/axom/work/axom-0.7.0/src/axom/sidre/core/MFEMSidreDataCollection.cpp:1508:33: error: no member named 'GetElementIntRule' in 'mfem::QuadratureSpaceBase'
                qf->GetSpace()->GetElementIntRule(0).GetOrder(),
                ~~~~~~~~~~~~~~  ^
1 warning and 1 error generated.
```

FreeBSD 13.2
